
install:
	sudo apt-get install python3-pip
	sudo pip3 install matplotlib
	sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-1.3.0-cp34-cp34m-linux_x86_64.whl
#	sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.3.0-cp34-cp34m-linux_x86_64.whl
