#language: c

sudo: required
dist: trusty

notifications:
  email: false

before_script:
# travis has changed to 64-bit and we require 32-bit compatibility libraries
  - sudo apt-get update
  - "sudo apt-get install -qq python3-pyqt5 pyqt5-dev pyqt5-dev-tools libreadline6 libreadline6-dev libgtk2.0-dev libgtk-3-dev || true"
  - "sudo apt-get install -qq gcc-arm-none-eabi || true"
  - "sudo apt-get install -qq gcc-arm-linux-gnueabi || true"
  - "sudo apt-get install -qq g++-arm-linux-gnueabi || true"
  - "sudo apt-get install -qq cmake uuid-dev libboost-dev || true"
  - "sudo apt-get install -qq qemu scons nasm || true"
  - "sudo apt-get install -qq libstdc++6:i386 || true"
  - "sudo apt-get install -qq lib32stdc++6 || true"

script:
  - cd release/ascore
  - scons posix > /dev/null
  - scons versatilepb > /dev/null
#  - scons x86 > /dev/null
  - cd ../../release/asboot
  - scons posix > /dev/null
  - scons versatilepb > /dev/null
  - cd ../../release/aslua && make cleanaws && make 91 > /dev/null && make 93 > /dev/null
#  - cd ../../release/astcpip/lwip && rm ../../download/lwip-contrib -fr && make aslwip > /dev/null && make all > /dev/null
# - cd ../../../release/aslinux && mkdir build && cd build && ln -fs ../script/vexpress-ca9.mk Makefile && make askernel > /dev/null
  - cd ../../release/askar && python ./ctest.py all
  - cd ../../release/askar && export schedfifo=yes && make clean > /dev/null && python ./ctest.py all

env:
  - EMAIL='parai@foxmail.com'

