/*
* Configuration of module: Port (Port_Cfg.c)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    STM32_F107
*
* Module vendor:           ArcCore
* Generator version:       null
*
* Generated by Arctic Studio (http://arccore.com) 
*/

/* parai: 2015-7-18
 * configuration for uC/eval-STM32F107 */

	
#include "stm32f10x_gpio.h"
#include "Port.h"

const uint32 remaps[] = {
	GPIO_Remap2_CAN1,
	GPIO_Remap_ETH,
	GPIO_Remap_CAN2,
	GPIO_Remap_USART2
};

const GpioPinCnfMode_Type GPIOConf[] =
{
  {	/* GPIO A */
	.GpioPinCnfMode_0 = 0, 	
	.GpioPinCnfMode_1 = 0, 	
	.GpioPinCnfMode_2 = 0, 	
	.GpioPinCnfMode_3 = 0, 	
	.GpioPinCnfMode_4 = 0, 	
	.GpioPinCnfMode_5 = 0, 	
	.GpioPinCnfMode_6 = 0, 	
	.GpioPinCnfMode_7 = 0, 	
	.GpioPinCnfMode_8 = 0, 	
	.GpioPinCnfMode_9 = 0, 	
	.GpioPinCnfMode_10 = 0, 	
	.GpioPinCnfMode_11 = 0, 	
	.GpioPinCnfMode_12 = 0, 	
	.GpioPinCnfMode_13 = 0, 	
	.GpioPinCnfMode_14 = 0, 	
	.GpioPinCnfMode_15 = 0, 		
  },
  { /* GPIO B */
	.GpioPinCnfMode_0 = 0, 	
	.GpioPinCnfMode_1 = 0, 	
	.GpioPinCnfMode_2 = 0, 	
	.GpioPinCnfMode_3 = 0, 	
	.GpioPinCnfMode_4 = 0, 	
	.GpioPinCnfMode_5 = 0, 	
	.GpioPinCnfMode_6 = 0, 	
	.GpioPinCnfMode_7 = 0, 	
	.GpioPinCnfMode_8 = 0, 	
	.GpioPinCnfMode_9 = 0, 	
	.GpioPinCnfMode_10 = 0, 	
	.GpioPinCnfMode_11 = 0, 	
	.GpioPinCnfMode_12 = 0, 	
	.GpioPinCnfMode_13 = 0, 	
	.GpioPinCnfMode_14 = 0, 	
	.GpioPinCnfMode_15 = 0, 		
  },
  { /* GPIO C */
	.GpioPinCnfMode_0 = 0, 	
	.GpioPinCnfMode_1 = 0, 	
	.GpioPinCnfMode_2 = 0, 	
	.GpioPinCnfMode_3 = 0, 	
	.GpioPinCnfMode_4 = 0, 	
	.GpioPinCnfMode_5 = 0, 	
	.GpioPinCnfMode_6 = 0, 	
	.GpioPinCnfMode_7 = 0, 	
	.GpioPinCnfMode_8 = 0, 	
	.GpioPinCnfMode_9 = 0, 	
	.GpioPinCnfMode_10 = 0, 	
	.GpioPinCnfMode_11 = 0, 	
	.GpioPinCnfMode_12 = 0, 	
	.GpioPinCnfMode_13 = 0, 	
	.GpioPinCnfMode_14 = 0, 	
	.GpioPinCnfMode_15 = 0, 		
  },
  { /* GPIO D */
	.GpioPinCnfMode_0 = GPIO_INPUT_MODE | GPIO_INPUT_PULLUP_CNF, 			/* CAN1 RX */
	.GpioPinCnfMode_1 = GPIO_OUTPUT_10MHz_MODE | GPIO_ALT_PUSHPULL_CNF, 	/* CAN1 TX */
	.GpioPinCnfMode_2 = 0, 	
	.GpioPinCnfMode_3 = 0,
	.GpioPinCnfMode_4 = 0,
	.GpioPinCnfMode_5 = GPIO_OUTPUT_50MHz_MODE | GPIO_ALT_PUSHPULL_CNF, 	/* USART2_TX  */
	.GpioPinCnfMode_6 = GPIO_INPUT_MODE | GPIO_FLOATING_INPUT_CNF, 			/* USART2_RX  */
	.GpioPinCnfMode_7 = 0, 	
	.GpioPinCnfMode_8 = 0, 	
	.GpioPinCnfMode_9 = 0, 	
	.GpioPinCnfMode_10 = 0, 	
	.GpioPinCnfMode_11 = 0, 	
	.GpioPinCnfMode_12 = 0, 	
	.GpioPinCnfMode_13 = GPIO_OUTPUT_10MHz_MODE | GPIO_OUTPUT_PUSHPULL_CNF,	/* LED1 */
	.GpioPinCnfMode_14 = GPIO_OUTPUT_10MHz_MODE | GPIO_OUTPUT_PUSHPULL_CNF,	/* LED2 */
	.GpioPinCnfMode_15 = GPIO_OUTPUT_10MHz_MODE | GPIO_OUTPUT_PUSHPULL_CNF,	/* LED3 */
  },
  { /* GPIO E */
	.GpioPinCnfMode_0 = 0, 	
	.GpioPinCnfMode_1 = 0, 	
	.GpioPinCnfMode_2 = 0, 	
	.GpioPinCnfMode_3 = 0, 	
	.GpioPinCnfMode_4 = 0, 	
	.GpioPinCnfMode_5 = 0, 	
	.GpioPinCnfMode_6 = 0, 	
	.GpioPinCnfMode_7 = 0, 	
	.GpioPinCnfMode_8 = 0, 	
	.GpioPinCnfMode_9 = 0, 	
	.GpioPinCnfMode_10 = 0, 	
	.GpioPinCnfMode_11 = 0, 	
	.GpioPinCnfMode_12 = 0, 	
	.GpioPinCnfMode_13 = 0, 	
	.GpioPinCnfMode_14 = 0,
	.GpioPinCnfMode_15 = 0, 		
  },
  { /* GPIO F */
	.GpioPinCnfMode_0 = 0, 	
	.GpioPinCnfMode_1 = 0, 	
	.GpioPinCnfMode_2 = 0, 	
	.GpioPinCnfMode_3 = 0, 	
	.GpioPinCnfMode_4 = 0, 	
	.GpioPinCnfMode_5 = 0, 	
	.GpioPinCnfMode_6 = 0, 	
	.GpioPinCnfMode_7 = 0, 	
	.GpioPinCnfMode_8 = 0, 	
	.GpioPinCnfMode_9 = 0, 	
	.GpioPinCnfMode_10 = 0, 	
	.GpioPinCnfMode_11 = 0, 	
	.GpioPinCnfMode_12 = 0, 	
	.GpioPinCnfMode_13 = 0, 	
	.GpioPinCnfMode_14 = 0, 	
	.GpioPinCnfMode_15 = 0, 		
  },
  { /* GPIO G */
	.GpioPinCnfMode_0 = 0, 	
	.GpioPinCnfMode_1 = 0, 	
	.GpioPinCnfMode_2 = 0, 	
	.GpioPinCnfMode_3 = 0, 	
	.GpioPinCnfMode_4 = 0, 	
	.GpioPinCnfMode_5 = 0, 	
	.GpioPinCnfMode_6 = 0, 	
	.GpioPinCnfMode_7 = 0, 	
	.GpioPinCnfMode_8 = 0, 	
	.GpioPinCnfMode_9 = 0, 	
	.GpioPinCnfMode_10 = 0, 	
	.GpioPinCnfMode_11 = 0, 	
	.GpioPinCnfMode_12 = 0, 	
	.GpioPinCnfMode_13 = 0, 	
	.GpioPinCnfMode_14 = 0, 	
	.GpioPinCnfMode_15 = 0, 		
  },
};


const GpioPinOutLevel_Type GPIOOutConf[] =
{
  {	/* GPIO A */
	.GpioPinOutLevel_0 = 0, 	
	.GpioPinOutLevel_1 = 0, 	
	.GpioPinOutLevel_2 = 0, 	
	.GpioPinOutLevel_3 = 0, 	
	.GpioPinOutLevel_4 = 0, 	
	.GpioPinOutLevel_5 = 0, 	
	.GpioPinOutLevel_6 = 0, 	
	.GpioPinOutLevel_7 = 0, 	
	.GpioPinOutLevel_8 = 0, 	
	.GpioPinOutLevel_9 = 0, 	
	.GpioPinOutLevel_10 = 0, 	
	.GpioPinOutLevel_11 = 0, 	
	.GpioPinOutLevel_12 = 0, 	
	.GpioPinOutLevel_13 = 0, 	
	.GpioPinOutLevel_14 = 0, 	
	.GpioPinOutLevel_15 = 0, 		
  },
  { /* GPIO B */
	.GpioPinOutLevel_0 = 0, 	
	.GpioPinOutLevel_1 = 0, 	
	.GpioPinOutLevel_2 = 0, 	
	.GpioPinOutLevel_3 = 0, 	
	.GpioPinOutLevel_4 = 0, 	
	.GpioPinOutLevel_5 = 0, 	
	.GpioPinOutLevel_6 = 0, 	
	.GpioPinOutLevel_7 = 0, 	
	.GpioPinOutLevel_8 = 0, 	
	.GpioPinOutLevel_9 = 0, 	
	.GpioPinOutLevel_10 = 0, 	
	.GpioPinOutLevel_11 = 0, 	
	.GpioPinOutLevel_12 = 0, 	
	.GpioPinOutLevel_13 = 0, 	
	.GpioPinOutLevel_14 = 0, 	
	.GpioPinOutLevel_15 = 0, 		
  },
  { /* GPIO C */
	.GpioPinOutLevel_0 = 0, 	
	.GpioPinOutLevel_1 = 0, 	
	.GpioPinOutLevel_2 = 0, 	
	.GpioPinOutLevel_3 = 0, 	
	.GpioPinOutLevel_4 = 0, 	
	.GpioPinOutLevel_5 = 0, 	
	.GpioPinOutLevel_6 = 0, 	
	.GpioPinOutLevel_7 = 0, 	
	.GpioPinOutLevel_8 = 0, 	
	.GpioPinOutLevel_9 = 0, 	
	.GpioPinOutLevel_10 = 0, 	
	.GpioPinOutLevel_11 = 0, 	
	.GpioPinOutLevel_12 = 0, 	
	.GpioPinOutLevel_13 = 0, 	
	.GpioPinOutLevel_14 = 0, 	
	.GpioPinOutLevel_15 = 0, 		
  },
  { /* GPIO D */
	.GpioPinOutLevel_0 = GPIO_OUTPUT_LOW, 		/* CAN1 RX */
	.GpioPinOutLevel_1 = GPIO_OUTPUT_LOW, 		/* CAN1 TX */
	.GpioPinOutLevel_2 = 0, 	
	.GpioPinOutLevel_3 = 0,
	.GpioPinOutLevel_4 = 0, 	
	.GpioPinOutLevel_5 = 0, 	
	.GpioPinOutLevel_6 = 0, 	
	.GpioPinOutLevel_7 = 0, 	
	.GpioPinOutLevel_8 = 0, 	
	.GpioPinOutLevel_9 = 0, 	
	.GpioPinOutLevel_10 = 0, 	
	.GpioPinOutLevel_11 = 0, 	
	.GpioPinOutLevel_12 = 0, 	
	.GpioPinOutLevel_13 = GPIO_OUTPUT_HIGH,		/* LED1 */
	.GpioPinOutLevel_14 = GPIO_OUTPUT_HIGH,		/* LED2 */
	.GpioPinOutLevel_15 = GPIO_OUTPUT_HIGH,		/* LED3 */
  },
  { /* GPIO E */
	.GpioPinOutLevel_0 = 0, 	
	.GpioPinOutLevel_1 = 0, 	
	.GpioPinOutLevel_2 = 0, 	
	.GpioPinOutLevel_3 = 0, 	
	.GpioPinOutLevel_4 = 0, 	
	.GpioPinOutLevel_5 = 0, 	
	.GpioPinOutLevel_6 = 0, 	
	.GpioPinOutLevel_7 = 0, 	
	.GpioPinOutLevel_8 = 0, 	
	.GpioPinOutLevel_9 = 0, 	
	.GpioPinOutLevel_10 = 0, 	
	.GpioPinOutLevel_11 = 0, 	
	.GpioPinOutLevel_12 = 0, 	
	.GpioPinOutLevel_13 = 0, 	
	.GpioPinOutLevel_14 = 0,
	.GpioPinOutLevel_15 = 0, 		
  },
  { /* GPIO F */
	.GpioPinOutLevel_0 = 0, 	
	.GpioPinOutLevel_1 = 0, 	
	.GpioPinOutLevel_2 = 0, 	
	.GpioPinOutLevel_3 = 0, 	
	.GpioPinOutLevel_4 = 0, 	
	.GpioPinOutLevel_5 = 0, 	
	.GpioPinOutLevel_6 = 0, 	
	.GpioPinOutLevel_7 = 0, 	
	.GpioPinOutLevel_8 = 0, 	
	.GpioPinOutLevel_9 = 0, 	
	.GpioPinOutLevel_10 = 0, 	
	.GpioPinOutLevel_11 = 0, 	
	.GpioPinOutLevel_12 = 0, 	
	.GpioPinOutLevel_13 = 0, 	
	.GpioPinOutLevel_14 = 0, 	
	.GpioPinOutLevel_15 = 0, 		
  },
  { /* GPIO G */
	.GpioPinOutLevel_0 = 0, 	
	.GpioPinOutLevel_1 = 0, 	
	.GpioPinOutLevel_2 = 0, 	
	.GpioPinOutLevel_3 = 0, 	
	.GpioPinOutLevel_4 = 0, 	
	.GpioPinOutLevel_5 = 0, 	
	.GpioPinOutLevel_6 = 0, 	
	.GpioPinOutLevel_7 = 0, 	
	.GpioPinOutLevel_8 = 0, 	
	.GpioPinOutLevel_9 = 0, 	
	.GpioPinOutLevel_10 = 0, 	
	.GpioPinOutLevel_11 = 0, 	
	.GpioPinOutLevel_12 = 0, 	
	.GpioPinOutLevel_13 = 0, 	
	.GpioPinOutLevel_14 = 0, 	
	.GpioPinOutLevel_15 = 0, 		
  },
};

const Port_ConfigType PortConfigData =
{
	.padCnt = 7,
	.padConfig = GPIOConf,
	.outConfig = GPIOOutConf,

    .remapCount = sizeof(remaps) / sizeof(uint32),
    .remaps = &remaps[0]
};
