/**
    @file             Can_Cfg.h
    @version          2.0.0

    @brief            AUTOSAR Can module interface
    @details          Configuration settings generated by user settings.

    Project           AUTOSAR 3.0 MCAL
    Platform          PA
    Peripheral        FLEXCAN
    Dependencies      

    ARVersion         3.0.0
    ARRevision        ASR_REL_3_0_REV_0003
    ARConfVariant
    SWVersion         2.0.0
    BuildVersion      XPC563xM_MCAL_2_0_0_RTM_ASR_REL_3_0_REV_0003_20111223

    (c) Copyright 2006-2011 Freescale Semiconductor Inc. & STMicroelectronics
    All Rights Reserved.
*/
/*==================================================================================================
==================================================================================================*/


/**
@file    Can_Cfg.h
@brief   (CAN023) The consistency of the configuration must be checked by the configuration tool(s).
@brief   (CAN022) The code configurator of the Can module is CAN controller specific.
         If the CAN controller is sited on-chip, the code generation tool for the Can module is Controller specific.
         If the CAN controller is an external device the generation tool must not be Controller specific.
@brief   (CAN024) The valid values that can be configured are hardware dependent.
         Therefore the rules and constraints can't be given in the standard.
         The configuration tool is responsible to do a static configuration checking, also regarding dependencies between modules (i.e. Port driver, MCU driver etc.)
@remarks Covers CAN023, CAN022, CAN024
@remarks Implements DCAN00023, DCAN00022, DCAN00024
*/

#ifndef _CAN_CFG_H_
#define _CAN_CFG_H_


/*==================================================================================================
                                    SOURCE FILE VERSION INFORMATION
==================================================================================================*/
/**
@{
@brief    The integration of incompatible files shall be avoided.
*/
#define CAN_AR_MAJOR_VERSION_CFG_H  3
#define CAN_AR_MINOR_VERSION_CFG_H  0
#define CAN_AR_PATCH_VERSION_CFG_H  0
#define CAN_SW_MAJOR_VERSION_CFG_H  2
#define CAN_SW_MINOR_VERSION_CFG_H  0
#define CAN_SW_PATCH_VERSION_CFG_H  0
/**@}*/





/**
@{
@brief    Can Controllers. Defines for conversion between object names and object IDs.
          (PR-MCAL-2944)Numeric ID's in configuration and definition of symbolic names in Can_Cfg.h file.
*/
/* Default configuration for FlexCAN_A */
#define CanController_0 (uint8)0U
        
/**@}*/


/**
@{
@brief    Can Controller Configurations.
          (PR-MCAL-2944)Numeric ID's in configuration and definition of symbolic names in Can_Cfg.h file.
*/
/* Default configuration for CanController ID=0, FlexCAN_A */
#define CanController_0_config (uint8)0U
        
/**@}*/


/**
@{
@brief    HOH - Can Hardware Objects.
          These defines (IDs) are extracted from the CanObjectId paremeter.
@brief    (PR-MCAL-2944)Numeric ID's in configuration and definition of symbolic names in Can_Cfg.h file.
@brief    (PR-MCAL-3031)Restriction: The HRHs and the HTHs shall be grouped, where HRHs come first.
          Example: HRH0 - 0, HRH1 - 1, HTH0 - 2, HTH1 - 3
          This must especially be supported for configurations containing several controllers what in this case means that
            the HRHs of all controllers are grouped before the HTHs of all controllers (there must not be any HTH of any controller
            with an object ID lower than that of any HRH configured for this driver).
*/

#define CanHardwareObject_0 0U /* RECEIVE object of Can Controller ID = 0 */
#define CanHardwareObject_1 1U /* TRANSMIT object of Can Controller ID = 0 */




/**@}*/


/**
@brief    Extended identifiers.
           - (STD_ON)  - if at least one extended identifier is used.
           - (STD_OFF) - if no extended identifiers are used at all
          If no extended identifiers are used then the IDs and MASKs can be stored in uint16 rather than uint32.
*/
#define CAN_EXTENDEDID (STD_ON)


/**
@brief    Switches the Development Error Detection and Notification ON or OFF.
@brief    (CAN028) Call the Development Error Tracer when DET is switched on and the Can module detects an error.
@brief    (CAN082) The detection of development errors is configurable (ON / OFF) at pre- compile time.
            The switch CanDevErrorDetection (see chapter 10) shall activate or deactivate the detection of all development errors.
@remarks  Covers CAN028, CAN082
@remarks  Implements DCAN00028, DCAN00082
*/
#define CAN_DEV_ERROR_DETECT (STD_ON)


/**
@brief    CAN driver support for wakeup over CAN Bus.
*/
#define CAN_WAKEUP_SUPPORT (STD_OFF)


/**
@brief    Extended number of can hardware objects:
           - STD_ON if more than 256 can hardware objects are needed (up to 65536)
           - STD_OFF if no more than 256 can hardware objects are needed
          The specification only allows up to 256 can hardware objects. The driver supports a non-standard extension of this limit.
*/
#define CAN_MBCOUNTEXTENSION (STD_OFF)


/**
@brief    Support for version info API
@brief    (CAN252) The function Can_GetGetVersionInfo shall be pre compile time configurable On/Off by the configuration parameter: CanVersionInfoApi.
@remarks  Covers CAN252
@remarks  Implements DCAN00252
*/
#define CAN_VERSION_INFO_API (STD_ON)


/**
@brief    Support for Multiplexed Transmision - MB set for Tx is put on bus from any TxMB that is available (free).
@brief    (CAN277) The Can module shall allow that the functionality Multiplexed Transmission is statically configurable (ON | OFF) at pre-compile time.
@remarks  Covers CAN277
@remarks  Implements DCAN00277
*/
#define CAN_TXMUX_SUPPORTED (STD_ON)


/**
@brief    Support for Transmision Cancellation
@brief    (CAN278) The Can module shall allow that the functionality Transmit Cancellation is statically configurable (ON | OFF) at pre-compile time.
@remarks  Covers CAN278
@remarks  Implements DCAN00278
*/
#define CAN_TXCANCEL_SUPPORTED (STD_ON)


/**
@brief    Support for Special MB Abort API
@brief    Enable an additional API, to write an ABORT code (b1001) to the MBCB filed of the MB to abort a message transmission.
*/
#define CAN_API_ENABLE_ABORT_MB (STD_OFF)

/**
@brief    Instance # of the driver - used for Det_ReportError().
*/
#define CAN_INSTANCE (uint8)0U


/**
@brief    Platform support mix of controllers with 64 and 32 MBs.
*/
#define CAN_MIX_MB_SUPPORT  (STD_ON)


/**
@{
@brief    Maximum number of Message Buffers configured.
*/

#define CAN_MAXMBCOUNT_0 (Can_HWObjectCountType)2U

/**@}*/

/**
@brief    Maximum possible Message Buffers per controller specific to this platform.
*/
#define CAN_MAXMB_SUPPORTED 64U

/**
@brief    Maximum possible CAN controllers per specific derivative.
*/
#define CAN_MAXCTRL_SUPPORTED (uint8)2U

/**
@{
@brief    Maximum No. of supported CAN controllers (vary according to Processor Family).
*/

#define CAN_MAXCONTROLLERCOUNT_0 (uint8)1U

/**@}*/


/**
@brief    (CAN099) The hardware events may be detected by an interrupt or by polling status flags of the hardware objects.
          The configuration possibilities regarding polling is hardware dependent (i.e. which events can be polled, which events need to be polled), and not restricted by this standard.
@brief    (CAN007)It shall be possible to configure the driver such that no interrupts at all are used (complete polling).
@remarks  Covers CAN099, CAN007
@remarks  Implements DCAN00099, DCAN00007
*/

/**
@{
@brief    These macros enable Interrupts for controllers if Tx processing is set to Interrupt Mode. */
#define CAN_A_TXINT_SUPPORTED  (STD_OFF)





/**@}*/

/**
@brief    This macro enables Can_MainFunction_Write() if at least one controller is set to process Tx in Polling Mode.
*/
#define CAN_TXPOLL_SUPPORTED   (STD_ON)



/**
@{
@brief    These macros enable Interrupts for controllers if Rx processing is set to Interrupt Mode.
*/
#define CAN_A_RXINT_SUPPORTED  (STD_OFF)





/**@}*/

/**
@brief    This macro enables Can_MainFunction_Read() if at least one controller is set to process Rx in Polling Mode.
*/
#define CAN_RXPOLL_SUPPORTED   (STD_ON)


/**
@{
@brief    These macros enable Interrupts for controllers if BusOff processing is set to Interrupt Mode.
*/
#define CAN_A_BUSOFFINT_SUPPORTED  (STD_OFF)





/**@}*/

/**
@brief    This macro enables Can_MainFunction_BusOff() if at least one controller is set to process BusOff in Polling Mode.
*/
#define CAN_BUSOFFPOLL_SUPPORTED   (STD_ON)


/**
@{
@brief    These macros enable Interrupts for controllers if Wakeup processing is set to Interrupt Mode.
*/
#define CAN_A_WAKEUPINT_SUPPORTED  (STD_OFF)





/**@}*/


/**
@brief    This macro enables Can_MainFunction_Wakeup() if at least one controller is set to process WakeUp in Polling Mode.
*/
#define CAN_WAKEUPPOLL_SUPPORTED   (STD_ON)


/**
@{
@brief    Maximum number of MB Filters configured.
*/
#define CAN_MAXFILTERCOUNT_0 (Can_HWObjectCountType)1U

/**@}*/

/**
@{
@brief    Maximum number of Filters configured for RxFifo.
*/
/**@}*/


/**
@brief    Support for Rx Fifo - If at least one controller supports RxFifo, then this define is set to STD_ON.
          This define is global for the entire hardware unit (all controllers). Every controller has particular
          configuration for Rx Fifo (see Can_ControllerConfigType structure).
*/
#define CAN_RXFIFO_ENABLE (STD_OFF)


/**
@brief    Set if Rx Fifo events (Warning/Overflow/FrameAvailable) are configured on the same int on INTC vector table.
          Based on this define separate interrupts handlers or not will be used for the 3 events of the RxFifo.
*/
#define CAN_RXFIFO_EVENT_UNIFIED (STD_ON)


/**
@brief    Indexes used for accessing the 'Can_ControlerDescriptorType' structure. NOTE that index order from hardware (where CAN_A has always index 0, ..)
            may not be the same with the order from the 'Can_ControlerDescriptorType' structure (where user can define controllers in any order).
          Count also the number of controllers that have interrupts enabled.
*/


/**
@brief    Index into the configuration structure.
          Can controllers can be declared in the Tressos plugin configuration in any order.
          Not necessary to have FLEXCAN_A on the first place. Some Can driver configurations can use only FLEXCAN_B for example.
*/
#define CAN_FCA_INDEX       (uint8)0U

/**
@brief    Index into the hardware platform.
*/
#define FLEXCAN_A_OFFSET    (uint8)0U

/**
@brief    RxFifo Functionality enabled/disabled. Used for Interrupts mapping in Can_Irq.c file.
          Every controller can have separate RxFifo enabled/disabled reported to other controllers.
*/
#define CAN_A_FIFO_EN       (STD_OFF)



/**
@brief    Optimization of interrupt service code for size.
          All MBs are handled by the same interrupt routine.
*/
#define CAN_ISROPTCODESIZE (STD_ON)


/**
@brief    Enable Non-Autosar API for Dual-Clock support.
          This can be set to STD_ON only if it is activated from Resource file (Can.CanConfig.DualClockMode = STD_ON)
*/
#define CAN_DUAL_CLOCK_MODE (STD_OFF)


/**
@brief   Maximum number of tight SW loops to execute while waiting for a state change
@brief   (CAN281) The Can module shall contain a timeout detection in case the hardware doesn't react in the expected time (hardware error) to prevent endless loops.
         As long as the system service does not provide a free running timer this timeout shall be realized with a fixed number of loops.
@brief   (CAN296)In that case, the Can module shall poll a flag of the CAN status register until the flag signals that the change takes affect and then return.
@remarks Covers CAN281, CAN296
@remarks Implements DCAN00281, DCAN00296
*/
#define CAN_TIMEOUT_DURATION (uint32)1000U


/**
@brief   PostBuild Support On.
@brief   (CAN221)VariantPB: (Mix of precompile and Post Build multiple selectableconfigurable configurations
@remarks Covers CAN221
@remarks Implements DCAN00221
*/
/* CAN_PRECOMPILE_SUPPORT must be defined only for Pre-Compile version. */



/**
@brief    Export Can_ConfigType structure. This is the type of the external data structure containing
            the overall initialization data for the CAN driver and affecting all controllers.
*/
#ifndef CAN_PRECOMPILE_SUPPORT

  /* Export Driver configuration */
  #define CAN_INIT_CONFIG_PB_DEFINES \
    extern CONST(Can_ConfigType, CAN_CONST) CanConfigSet_0; 


  /* Export Controllers configuration */
  #define CAN_INIT_CONFIG_CONTROLLERS_PB \
    extern CONST(Can_ControllerConfigType, CAN_CONST) ControllerConfigs0_PB[CAN_MAXCONTROLLERCOUNT_0];

#endif


/**
@brief    Periods for cyclic call of Main function
@brief    (CAN355)CanMainFunctionBusoffPeriod - This parameter describes the period for cyclic call to Can_MainFunction_Busoff. Unit is seconds.
@remarks  Covers CAN355
@remarks  Implements DCAN00355
*/
#define CAN_MAINFUNCTION_PERIOD_BUSOFF  (uint32)0.0010U

/**
@brief    Periods for cyclic call of Main function
@brief    (CAN356)CanMainFunctionReadPeriod - This parameter describes the period for cyclic call to Can_MainFunction_Read. Unit is seconds.
@remarks  Covers CAN356
@remarks  Implements DCAN00356
*/
#define CAN_MAINFUNCTION_PERIOD_READ    (uint32)0.0010U

/**
@brief    Periods for cyclic call of Main function
@brief    (CAN357)CanMainFunctionWakeupPeriod - This parameter describes the period for cyclic call to Can_MainFunction_Wakeup. Unit is seconds.
@remarks  Covers CAN357
@remarks  Implements DCAN00357
*/
#define CAN_MAINFUNCTION_PERIOD_WAKEUP  (uint32)0.0010U

/**
@brief    Periods for cyclic call of Main function
@brief    (CAN358)CanMainFunctionWritePeriod - This parameter describes the period for cyclic call to Can_MainFunction_Write. Unit is seconds.
@remarks  Covers CAN358
@remarks  Implements DCAN00358
*/
#define CAN_MAINFUNCTION_PERIOD_WRITE   (uint32)0.0010U


/**
@brief    WakeUp support settings.
          Internal Wakeup is triggered by WakeUp bits Interrupt from IntVectorTable.
*/
#define CAN_WKP_INT_SUPPORT   (STD_ON)
/**
@brief    WakeUp support settings.
          External Wakeup is supported by Rx pin through WAKEUP_UNIT module.
*/
#define CAN_WKP_EXT_SUPPORT   (STD_OFF)





/**
@brief    Defines if Backwards Compatibility Configuration (BCC) feature of CAN controller is used in the configuration.
          If BCC feature of CAN controller is enabled, Individual Rx masking and queue feature are disabled.
          If BCC feature of CAN controller is disabled, Individual Rx masking and queue feature are enabled.
*/
#define CAN_BCC_SUPPORT_ENABLE (STD_OFF)

/**
@brief    Macro used to define the maximum of Can object IDs configured  .
*/
#define CAN_MAX_OBJECT_ID (Can_HWObjectCountType)2U


#endif /* _CAN_CFG_H_ */
