import os

Import('asenv')
BOARD = asenv['BOARD']

objs = []

objs += SConscript('board.%s/SConscript'%(BOARD))
objs += SConscript('common/SConscript')
objs += SConscript('swc/SConscript')
Return('objs')